<?php

return [
    [
        "id" => 1,
        "title" => "Appartamento al Centro Storico",
        "description" => "Accogliente appartamento nel cuore della città, vicino a tutti i servizi.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 3,
        "mq" => 80,
        "address" => "Via Roma 1, Roma",
        "lat" => "42.1718169",
        "long" => "12.5919801",
        "image" => "https://trovacasacomo.it/preview/5936/imm_3303-1200-800.jpg"
    ],
    [
        "id" => 2,
        "title" => "Villetta con Giardino",
        "description" => "Spaziosa villetta immersa nel verde con giardino privato.",
        "beds" => 4,
        "bathrooms" => 2,
        "rooms" => 5,
        "mq" => 150,
        "address" => "Via dei Giardini 10, Milano",
        "lat" => "45.464203",
        "long" => "9.189982",
        "image" => "https://www.casavacanzeaffitti.it/wp-content/uploads/2021/02/IMG_3366.jpg"
    ],
    [
        "id" => 3,
        "title" => "Attico Vista Mare",
        "description" => "Luminoso attico con splendida vista sul mare.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 120,
        "address" => "Via del Mare 5, Napoli",
        "lat" => "40.851798",
        "long" => "14.268120",
        "image" => "https://www.hotelmeeting.com/wp-content/uploads/2021/07/5038.jpg"
    ],
    [
        "id" => 4,
        "title" => "Appartamento Moderno",
        "description" => "Appartamento completamente ristrutturato in stile moderno.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 3,
        "mq" => 90,
        "address" => "Via Garibaldi 15, Torino",
        "lat" => "45.070312",
        "long" => "7.686856",
        "image" => "https://www.startpreventivi.it/wp-content/themes/Avada-Child-Theme/images/Blog/Case-Appartamenti/Appartamento-moderno-elegante/5-appartamento-moderno-elegante.jpg"
    ],
    [
        "id" => 5,
        "title" => "Casa Vacanze sul Lago",
        "description" => "Casa vacanze con accesso diretto al lago e vista panoramica.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 3,
        "mq" => 100,
        "lat" => "45.808059",
        "long" => "9.085176",
        "address" => "Via Lungolago 20, Como",
        "image" => "https://blog.casa.it/wp-content/uploads/2014/06/casa_al_lago6.jpg"
    ],
    [
        "id" => 6,
        "title" => "Appartamento in Zona Universitaria",
        "description" => "Perfetto per studenti, a pochi passi dall'università.",
        "beds" => 1,
        "bathrooms" => 1,
        "rooms" => 2,
        "mq" => 60,
        "lat" => "44.494887",
        "long" => "11.342616",
        "address" => "Via Zamboni 33, Bologna",
        "image" => "https://www.leresidenzedelcampus.it/wp-content/uploads/2016/03/affitto-appartamenti-parma.jpg"
    ],
    [
        "id" => 7,
        "title" => "Appartamento in Villa d'Epoca",
        "description" => "Splendido appartamento in villa d'epoca, immerso nel verde.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 130,
        "address" => "Via Verdi 5, Firenze",
        "lat" => "43.769562",
        "long" => "11.255814",
        "image" => "https://trepievi.com/wp-content/uploads/2021/09/Esterni-Appartamenti-Menaggio-Rif.MA023H-14_rid.jpg"
    ],
    [
        "id" => 8,
        "title" => "Monolocale Arredato",
        "description" => "Monolocale completamente arredato in zona centrale.",
        "beds" => 1,
        "bathrooms" => 1,
        "rooms" => 1,
        "mq" => 40,
        "address" => "Corso Umberto I 10, Bari",
        "lat" => "41.117143",
        "long" => "16.871871",
        "image" => "https://mondodesign.it/wp-content/uploads/2016/07/Arredare-Monolocale-86.jpg"
    ],
    [
        "id" => 9,
        "title" => "Trilocale con Vista",
        "description" => "Appartamento trilocale con vista mozzafiato sulla città.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 3,
        "mq" => 85,
        "address" => "Via Toledo 12, Napoli",
        "lat" => "40.851798",
        "long" => "14.268120",
        "image" => "https://it.gardalive.com/var/21925/storage/images/media/immagini/ufficio-manerba/man200/man200-3/614941-1-ita-IT/man200-3_full25.jpg"
    ],
    [
        "id" => 10,
        "title" => "Loft Industriale",
        "description" => "Loft dal design industriale in ex fabbrica ristrutturata.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 2,
        "mq" => 100,
        "address" => "Via Bovisasca 16, Milano",
        "lat" => "45.464203",
        "long" => "9.189982",
        "image" => "https://cdn.home-designing.com/wp-content/uploads/2015/03/wood-paneled-loft.jpg"
    ],
    [
        "id" => 11,
        "title" => "Appartamento con Terrazzo Panoramico",
        "description" => "Splendido appartamento con terrazzo panoramico e vista sulla città.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 3,
        "mq" => 85,
        "address" => "Via delle Rose 10, Verona",
        "lat" => "45.438256",
        "long" => "10.991622",
        "image" => "https://www.apartments.com/blog/sites/default/files/styles/x_large/public/image/2023-06/apartment-kitchen.jpg.webp?itok=bd9ds5dP.jpg"
    ],
    [
        "id" => 12,
        "title" => "Appartamento Elegante in Centro",
        "description" => "Elegante appartamento nel cuore del centro città, vicino ai principali luoghi di interesse.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 120,
        "address" => "Piazza del Duomo 1, Milano",
        "lat" => "45.465421",
        "long" => "9.185924",
        "image" => "http://t0.gstatic.com/licensed-image?q=tbn:ANd9GcRzCbWjPwksIzlsAiiJRjOUBV2zMTv9tuzR50vepTggELpajZyYcPYUGpL3PUJ1vawUqA16DFgUdpeUl2OWfB4.jpg"
    ],
    [
        "id" => 13,
        "title" => "Bilocale Moderno e Luminoso",
        "description" => "Bilocale moderno e luminoso, con arredamento contemporaneo e ampi spazi.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 2,
        "mq" => 70,
        "address" => "Corso Vittorio Emanuele 5, Roma",
        "lat" => "41.893056",
        "long" => "12.482778",
        "image" => "http://t3.gstatic.com/licensed-image?q=tbn:ANd9GcQeJfyZcjphYfbpv7Igoo-5DxaHmgM-xcZP7xrwJxl9kEz43lkW9G-nO72fx5XE7L8FMzdBBGSi1QYNKGpsDfE"
    ],
    [
        "id" => 14,
        "title" => "Casa Storica con Giardino",
        "description" => "Affascinante casa storica con ampio giardino privato e dettagli d'epoca.",
        "beds" => 4,
        "bathrooms" => 3,
        "rooms" => 6,
        "mq" => 200,
        "address" => "Via delle Magnolie 12, Firenze",
        "lat" => "43.769562",
        "long" => "11.255814",
        "image" => "http://t3.gstatic.com/licensed-image?q=tbn:ANd9GcSn2awRHLyko5FDK9or4yETdWyncxT99VC3g1MuuaWn3MMm2RGi9dw7YmMY20eF1m8eHkKh3MFYzfZOvIRKfJs"
    ],
    [
        "id" => 15,
        "title" => "Appartamento in Loft Ristrutturato",
        "description" => "Spazioso loft ristrutturato con elementi industriali e ampie finestre.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 3,
        "mq" => 100,
        "address" => "Via Industriale 25, Torino",
        "lat" => "45.070312",
        "long" => "7.686856",
        "image" => "http://t1.gstatic.com/licensed-image?q=tbn:ANd9GcTxJZTmS7GL78r5FPdolbpBxPaSYvl_xd3Es1yGz5lTqyK1fDbiycZ320YUpEPLGyyHaHbj4tscInBMpClLhYw"
    ],
    [
        "id" => 16,
        "title" => "Appartamento con Piscina Privata",
        "description" => "Lussuoso appartamento con piscina privata e giardino.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 140,
        "address" => "Via dei Fiori 8, Genova",
        "lat" => "44.405650",
        "long" => "8.946256",
        "image" => "https://www.grubbproperties.com/sites/default/files/blog/intelligent-building-design-1536x1024_0.jpg"
    ],
    [
        "id" => 17,
        "title" => "Monolocale in Zona Universitaria",
        "description" => "Accogliente monolocale ideale per studenti, vicino all'università.",
        "beds" => 1,
        "bathrooms" => 1,
        "rooms" => 1,
        "mq" => 45,
        "address" => "Via Università 15, Bologna",
        "lat" => "44.494887",
        "long" => "11.342616",
        "image" => "https://www.grubbproperties.com/sites/default/files/images/intelligent-construction-1024x684.jpg"
    ],
    [
        "id" => 18,
        "title" => "Appartamento con Vista sul Mare",
        "description" => "Meraviglioso appartamento con vista mozzafiato sul mare e terrazzo privato.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 130,
        "address" => "Lungomare 20, Napoli",
        "lat" => "40.851798",
        "long" => "14.268120",
        "image" => "https://www.grubbproperties.com/sites/default/files/images/lam_pool-1024x683.jpg"
    ],
    [
        "id" => 19,
        "title" => "Casa in Campagna",
        "description" => "Rinomata casa in campagna con ampio terreno e privacy.",
        "beds" => 5,
        "bathrooms" => 3,
        "rooms" => 7,
        "mq" => 250,
        "address" => "Strada delle Campagne 22, Siena",
        "lat" => "43.318000",
        "long" => "11.330000",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1200/s3/2/3585/link%20mint%20st_exterior%201.png"
    ],
    [
        "id" => 20,
        "title" => "Appartamento Centrale con Garage",
        "description" => "Comodo appartamento centrale con garage privato e vista sulla città.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 3,
        "mq" => 80,
        "address" => "Via Centrale 30, Trieste",
        "lat" => "45.649527",
        "long" => "13.767834",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1200/s3/2/3585/link%20mint%20st_exterior%202.png"
    ],
    [
        "id" => 21,
        "title" => "Appartamento per Famiglie",
        "description" => "Ideale per famiglie, con ampi spazi e vicino a scuole e parchi.",
        "beds" => 4,
        "bathrooms" => 2,
        "rooms" => 5,
        "mq" => 150,
        "address" => "Via dei Bambini 7, Roma",
        "lat" => "41.902782",
        "long" => "12.5919801",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1200/s3/2/3585/web%20version-26.jpg"
    ],
    [
        "id" => 22,
        "title" => "Appartamento con Spa Privata",
        "description" => "Esclusivo appartamento con spa privata e zona benessere.",
        "beds" => 2,
        "bathrooms" => 2,
        "rooms" => 3,
        "mq" => 110,
        "address" => "Via delle Terme 18, Bologna",
        "lat" => "44.494887",
        "long" => "11.342616",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1200/s3/2/3585/rooftop%20terrace%20edit.jpg"
    ],
    [
        "id"=> 23,
        "title"=> "Appartamento con Giardino e Barbecue",
        "description"=> "Spazioso appartamento con giardino privato e area barbecue, ideale per famiglie.",
        "beds"=> 3,
        "bathrooms"=> 2,
        "rooms"=> 4,
        "mq"=> 110,
        "address"=> "Via delle Palme 8, Catania",
        "lat"=> "37.507876",
        "long"=> "15.083560",
        "image"=> "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1200/s3/2/3585/pool%20w%20view%20edited.jpg"
    ],
    [
        "id" => 24,
        "title"=> "Attico con Vista Panoramica",
        "description"=> "Elegante attico con terrazza panoramica e vista mozzafiato sulla città.",
        "beds"=> 2,
        "bathrooms"=> 2,
        "rooms"=> 3,
        "mq"=> 95,
        "address"=> "Via San Lorenzo 12, Torino",
        "lat"=> "45.070312",
        "long"=> "7.686856",
        "image"=> "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1200/s3/2/3585/web%20version-3.jpg"
    ],
    [
        "id"=> 25,
        "title"=> "Appartamento Rustico in Montagna",
        "description"=> "Accogliente appartamento in stile rustico, situato in montagna con vista sui panorami naturali.",
        "beds"=> 4,
        "bathrooms"=> 2,
        "rooms"=> 4,
        "mq"=> 120,
        "address"=> "Strada delle Alpi 5, Cortina d'Ampezzo",
        "lat"=> "46.540298",
        "long"=> "12.019927",
        "image"=> "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1200/s3/2/3585/web%20version-18.jpg"
    ],
    [
        "id"=> 26,
        "title"=> "Appartamento con Piscina e Giardino",
        "description"=> "Lussuoso appartamento con piscina privata e giardino ben curato.",
        "beds"=> 3,
        "bathrooms"=> 2,
        "rooms"=> 4,
        "mq"=> 140,
        "address"=> "Via dei Fiori 22, Pisa",
        "lat"=> "43.722839",
        "long"=> "10.396595",
        "image"=> "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1200/s3/2/3585/web%20version-19.jpg"
    ],
    [
        "id"=> 27,
        "title"=> "Monolocale con Arredamento Designer",
        "description"=> "Moderno monolocale con arredamento di design e vista sulla città.",
        "beds"=> 1,
        "bathrooms"=> 1,
        "rooms"=> 1,
        "mq"=> 45,
        "address"=> "Via dei Designer 8, Milano",
        "lat"=> "45.464203",
        "long"=> "9.189982",
        "image"=> "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1200/s3/2/3585/web%20version-10.jpg"
    ],
    [
        "id"=> 28,
        "title"=> "Appartamento con Terrazzo e Vista sulla Collina",
        "description"=> "Elegante appartamento con ampio terrazzo e vista sulle colline circostanti.",
        "beds"=> 2,
        "bathrooms"=> 1,
        "rooms"=> 3,
        "mq"=> 90,
        "address"=> "Via delle Colline 10, Perugia",
        "lat"=> "43.112423",
        "long"=> "12.390827",
        "image"=> "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1200/s3/2/3585/web%20version-9.jpg"
    ],
    [
        "id"=> 29,
        "title"=> "Appartamento con Garage e Cantina",
        "description"=> "Appartamento spazioso con garage privato e cantina, situato in zona tranquilla.",
        "beds"=> 3,
        "bathrooms"=> 2,
        "rooms"=> 4,
        "mq"=> 110,
        "address"=> "Via del Garage 15, Bergamo",
        "lat"=> "45.698350",
        "long"=> "9.677268",
        "image"=> "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1200/s3/2/3585/web%20version-8.jpg"
    ],
    [
        "id"=> 30,
        "title"=> "Appartamento con Sauna Privata",
        "description"=> "Moderno appartamento con sauna privata e zona benessere, perfetto per rilassarsi.",
        "beds"=> 2,
        "bathrooms"=> 2,
        "rooms"=> 3,
        "mq"=> 100,
        "address"=> "Via delle Terme 25, Bologna",
        "lat"=> "44.494887",
        "long"=> "11.342616",
        "image"=> "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1200/s3/2/3585/web%20version-7.jpg"
    ],
    [
        "id"=> 31,
        "title"=> "Villa con Vista sul Mare",
        "description"=> "Elegante villa con vista mozzafiato sul mare, dotata di ampio giardino e piscina.",
        "beds"=> 5,
        "bathrooms"=> 3,
        "rooms"=> 6,
        "mq"=> 250,
        "address"=> "Via delle Onde 20, Rimini",
        "lat"=> "44.067803",
        "long"=> "12.568154",
        "image"=> "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1200/s3/2/3585/web%20version-6.jpg"
    ],
    [
        "id"=> 32,
        "title"=> "Appartamento in Palazzo Storico",
        "description"=> "Appartamento affascinante in un elegante palazzo storico, con dettagli d'epoca.",
        "beds"=> 3,
        "bathrooms"=> 2,
        "rooms"=> 4,
        "mq"=> 120,
        "address"=> "Via Storica 30, Firenze",
        "lat"=> "43.769562",
        "long"=> "11.255814",
        "image"=> "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1200/s3/2/3585/web%20version-5.jpg"
    ],
    [
        "id"=> 33,
        "title"=> "Loft con Vista sul Fiume",
        "description"=> "Moderno loft con ampie finestre e vista panoramica sul fiume.",
        "beds"=> 2,
        "bathrooms"=> 1,
        "rooms"=> 2,
        "mq"=> 80,
        "address"=> "Lungofiume 8, Torino",
        "lat"=> "45.070312",
        "long"=> "7.686856",
        "image"=> "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1200/s3/2/3585/web%20version-4.jpg"
    ],
    [
        "id"=> 34,
        "title"=> "Appartamento con Spa e Jacuzzi",
        "description"=> "Appartamento esclusivo con spa privata e jacuzzi, per un soggiorno di lusso.",
        "beds"=> 2,
        "bathrooms"=> 2,
        "rooms"=> 3,
        "mq"=> 110,
        "address"=> "Via della Spa 15, Roma",
        "lat"=> "41.893056",
        "long"=> "12.482778",
        "image"=> "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1110/s3/2/97682/9450-forest-springs-dr-dallas-tx-75243-high-res-8.jpg"
    ],
    [
        "id" => 35,
        "title" => "Attico con Terrazza e Vista sul Mare",
        "description" => "Elegante attico con grande terrazza e vista spettacolare sul mare.",
        "beds" => 4,
        "bathrooms" => 3,
        "rooms" => 5,
        "mq" => 150,
        "address" => "Lungomare 30, Salerno",
        "lat" => "40.682708",
        "long" => "14.765142",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1110/s3/2/97682/9450-forest-springs-dr-dallas-tx-75243-high-res-7.jpg"
    ],
    [
        "id" => 36,
        "title" => "Monolocale con Terrazzo",
        "description" => "Accogliente monolocale con ampio terrazzo, perfetto per il relax.",
        "beds" => 1,
        "bathrooms" => 1,
        "rooms" => 1,
        "mq" => 50,
        "address" => "Via del Sole 15, Genova",
        "lat" => "44.405650",
        "long" => "8.946256",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1110/s3/2/97682/9450-forest-springs-dr-dallas-tx-75243-high-res-6.jpg"
    ],
    [
        "id" => 37,
        "title" => "Appartamento con Vista sulla Collina",
        "description" => "Elegante appartamento con vista panoramica sulle colline circostanti.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 120,
        "address" => "Via delle Colline 25, Bologna",
        "lat" => "44.494887",
        "long" => "11.342616",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1110/s3/2/97682/9450-forest-springs-dr-dallas-tx-75243-high-res-5.jpg"
    ],
    [
        "id" => 38,
        "title" => "Villa con Piscina e Giardino",
        "description" => "Splendida villa con piscina privata e giardino ben curato.",
        "beds" => 6,
        "bathrooms" => 4,
        "rooms" => 8,
        "mq" => 300,
        "address" => "Via delle Rose 12, Rimini",
        "lat" => "44.067803",
        "long" => "12.568154",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1110/s3/2/97682/9450-forest-springs-dr-dallas-tx-75243-high-res-9.jpg"
    ],
    [
        "id" => 39,
        "title" => "Appartamento con Balcone e Vista Mare",
        "description" => "Accogliente appartamento con balcone e vista mozzafiato sul mare.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 2,
        "mq" => 70,
        "address" => "Via del Mare 10, Amalfi",
        "lat" => "40.633",
        "long" => "14.602",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1110/s3/2/97682/9450-forest-springs-dr-dallas-tx-75243-high-res-10.jpg"
    ],
    [
        "id" => 40,
        "title" => "Casa Vacanze con Giardino e Vista Lago",
        "description" => "Casa vacanze con giardino privato e splendida vista sul lago.",
        "beds" => 4,
        "bathrooms" => 2,
        "rooms" => 5,
        "mq" => 150,
        "address" => "Via del Lago 8, Como",
        "lat" => "45.808059",
        "long" => "9.085176",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1110/s3/2/97682/9450-forest-springs-dr-dallas-tx-75243-high-res-11.jpg"
    ],
    [
        "id" => 41,
        "title" => "Attico con Terrazza e Vista sulla Città",
        "description" => "Attico elegante con grande terrazza e vista panoramica sulla città.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 130,
        "address" => "Piazza San Marco 5, Venezia",
        "lat" => "45.4345",
        "long" => "12.3384",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1110/s3/2/97682/9450-forest-springs-dr-dallas-tx-75243-high-res-13.jpg"
    ],
    [
        "id" => 42,
        "title" => "Appartamento con Giardino e Area Relax",
        "description" => "Appartamento spazioso con giardino privato e area relax all'aperto.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 110,
        "address" => "Via delle Palme 10, Catania",
        "lat" => "37.507876",
        "long" => "15.083560",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1110/s3/2/97682/9450-forest-springs-dr-dallas-tx-75243-high-res-12.jpg"
    ],
    [
        "id" => 43,
        "title" => "Appartamento con Sauna e Spa",
        "description" => "Elegante appartamento con sauna privata e zona spa per un relax totale.",
        "beds" => 2,
        "bathrooms" => 2,
        "rooms" => 3,
        "mq" => 100,
        "address" => "Via delle Terme 30, Bologna",
        "lat" => "44.494887",
        "long" => "11.342616",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1110/s3/2/97682/9450-forest-springs-dr-dallas-tx-75243-high-res-16.jpg"
    ],
    [
        "id" => 44,
        "title" => "Appartamento con Garage e Terrazzo",
        "description" => "Spazioso appartamento con garage privato e grande terrazzo per godersi l'esterno.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 120,
        "address" => "Via del Garage 10, Bergamo",
        "lat" => "45.698350",
        "long" => "9.677268",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1110/s3/2/97682/9450-forest-springs-dr-dallas-tx-75243-high-res-17.jpg"
    ],
    [
        "id" => 45,
        "title" => "Loft con Arredamento Moderno",
        "description" => "Moderno loft con arredamento elegante e ampie finestre.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 2,
        "mq" => 85,
        "address" => "Via dei Design 5, Milano",
        "lat" => "45.464203",
        "long" => "9.189982",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1110/s3/2/97682/9450-forest-springs-dr-dallas-tx-75243-high-res-19.jpg"
    ],
    [
        "id" => 46,
        "title" => "Appartamento in Zona Tranquilla",
        "description" => "Accogliente appartamento situato in una zona tranquilla e residenziale.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 3,
        "mq" => 80,
        "address" => "Via del Silenzio 7, Torino",
        "lat" => "45.070312",
        "long" => "7.686856",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1110/s3/2/97682/9450-forest-springs-dr-dallas-tx-75243-high-res-20.jpg"
    ],
    [
        "id" => 47,
        "title" => "Villa con Giardino e Vista Mare",
        "description" => "Elegante villa con giardino privato e vista mozzafiato sul mare.",
        "beds" => 5,
        "bathrooms" => 3,
        "rooms" => 6,
        "mq" => 250,
        "address" => "Via del Mare 50, Cagliari",
        "lat" => "39.2238",
        "long" => "9.1216",
        "image" => "https://pnwapts.com/wp-content/uploads/2021/03/Link-14_2.jpg"
    ],
    [
        "id" => 48,
        "title" => "Appartamento con Vista sul Fiume",
        "description" => "Spazioso appartamento con vista panoramica sul fiume e arredi moderni.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 120,
        "address" => "Lungofiume 20, Torino",
        "lat" => "45.070312",
        "long" => "7.686856",
        "image" => "https://pnwapts.com/wp-content/uploads/2021/03/Link-14_3.jpg"
    ],
    [
        "id" => 49,
        "title" => "Monolocale con Giardino Privato",
        "description" => "Accogliente monolocale con giardino privato e spazi ben arredati.",
        "beds" => 1,
        "bathrooms" => 1,
        "rooms" => 1,
        "mq" => 55,
        "address" => "Via del Giardino 9, Pisa",
        "lat" => "43.722839",
        "long" => "10.396593",
        "image" => "https://pnwapts.com/wp-content/uploads/2021/03/Link-14_4.jpg"
    ],
    [
        "id" => 50,
        "title" => "Appartamento con Balcone e Vista Montagna",
        "description" => "Spazioso appartamento con balcone e vista panoramica sulle montagne.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 3,
        "mq" => 80,
        "address" => "Via delle Montagne 25, Aosta",
        "lat" => "45.7373",
        "long" => "7.3206",
        "image" => "https://pnwapts.com/wp-content/uploads/2021/03/Link-14_5.jpg"
    ],
    [
        "id" => 51,
        "title" => "Attico con Terrazza e la Città",
        "description" => "Attico moderno con terrazza panoramica e vista spettacolare sulla città.",
        "beds" => 4,
        "bathrooms" => 3,
        "rooms" => 5,
        "mq" => 150,
        "address" => "Piazza della Libertà 10, Milano",
        "lat" => "45.4642",
        "long" => "9.1899",
        "image" => "https://pnwapts.com/wp-content/uploads/2021/03/Link-14_6.jpg"
    ],
    [
        "id" => 52,
        "title" => "Appartamento con Camere Ample e Luminoso",
        "description" => "Luminoso appartamento con camere ampie e ben arredate.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 120,
        "address" => "Via della Luce 30, Roma",
        "lat" => "41.9028",
        "long" => "12.4964",
        "image" => "https://pnwapts.com/wp-content/uploads/2021/03/Link-14_7.jpg"
    ],
    [
        "id" => 53,
        "title" => "Casa con Vista Panoramica e Piscina",
        "description" => "Casa elegante con vista panoramica e piscina privata.",
        "beds" => 5,
        "bathrooms" => 3,
        "rooms" => 6,
        "mq" => 200,
        "address" => "Via del Panorama 15, Napoli",
        "lat" => "40.8522",
        "long" => "14.2681",
        "image" => "https://pnwapts.com/wp-content/uploads/2021/03/Link-14_8.jpg"
    ],
    [
        "id" => 54,
        "title" => "Appartamento con Terrazzo e Spazi Aperti",
        "description" => "Spazioso appartamento con terrazzo privato e aree aperte per rilassarsi.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 130,
        "address" => "Via degli Spazi 12, Firenze",
        "lat" => "43.7696",
        "long" => "11.2558",
        "image" => "https://pnwapts.com/wp-content/uploads/2021/03/Link-14_9.jpg"
    ],
    [
        "id" => 55,
        "title" => "Monolocale con Cucina Completa e Balcone",
        "description" => "Monolocale ben arredato con cucina completa e balcone privato.",
        "beds" => 1,
        "bathrooms" => 1,
        "rooms" => 1,
        "mq" => 60,
        "address" => "Via della Cucina 8, Verona",
        "lat" => "45.4384",
        "long" => "10.9916",
        "image" => "https://pnwapts.com/wp-content/uploads/2021/03/Link-14_10.jpg"
    ],
    [
        "id" => 56,
        "title" => "Appartamento con Terrazza e Vista Sul Giardino",
        "description" => "Accogliente appartamento con terrazza privata e vista sul giardino.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 2,
        "mq" => 70,
        "address" => "Via del Giardino 22, Siena",
        "lat" => "43.3188",
        "long" => "11.3308",
        "image" => "https://pnwapts.com/wp-content/uploads/2021/03/Link-14_11.jpg"
    ],
    [
        "id" => 57,
        "title" => "Villa con Ampio Parco e Piscina",
        "description" => "Elegante villa con ampio parco e piscina privata.",
        "beds" => 7,
        "bathrooms" => 4,
        "rooms" => 8,
        "mq" => 350,
        "address" => "Via del Parco 5, Pescara",
        "lat" => "42.4627",
        "long" => "14.2161",
        "image" => "https://resource.rentcafe.com/image/upload/x_0,y_0,w_1461,h_900,c_crop/q_auto,f_auto,c_limit,w_1440/s3/2/3585/deskins1_linkbroad_photofrommint(1).png"
    ],
    [
        "id" => 58,
        "title" => "Appartamento con Vista e Accesso alla Spiaggia",
        "description" => "Spazioso appartamento con vista mare e accesso diretto alla spiaggia.",
        "beds" => 4,
        "bathrooms" => 2,
        "rooms" => 5,
        "mq" => 140,
        "address" => "Lungomare 50, Rimini",
        "lat" => "44.0678",
        "long" => "12.5682",
        "image" => "https://resource.rentcafe.com/image/upload/x_0,y_0,w_1980,h_1321,c_crop/q_auto,f_auto,c_limit,w_1440/s3/2/3585/a1%20living%20room(1).jpg"
    ],
    [
        "id" => 59,
        "title" => "Attico con Terrazza e Vista sui Monti",
        "description" => "Moderno attico con terrazza e vista spettacolare sulle montagne.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 130,
        "address" => "Via dei Monti 10, Trento",
        "lat" => "46.0670",
        "long" => "11.1217",
        "image" => "https://static.dezeen.com/uploads/2022/08/gheorghe-puzzle-link-apartment-vienna-interiors_dezeen_2364_col_hero.jpg"
    ],
    [
        "id" => 60,
        "title" => "Appartamento con Giardino e Accesso Privato",
        "description" => "Elegante appartamento con giardino privato e accesso diretto alla zona verde.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 2,
        "mq" => 75,
        "address" => "Via del Verde 8, Bologna",
        "lat" => "44.4949",
        "long" => "11.3426",
        "image" => "https://interiorlover.in/wp-content/uploads/2021/04/Tanuja-Rana-Associates-9-800x534.jpg"
    ],
    [
        "id" => 61,
        "title" => "Loft con Arredi Vintage e Vista Urbana",
        "description" => "Loft unico con arredi vintage e vista panoramica sulla città.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 1,
        "mq" => 90,
        "address" => "Via degli Artisti 3, Milano",
        "lat" => "45.4642",
        "long" => "9.1899",
        "image" => "https://interiorlover.in/wp-content/uploads/2021/04/Tanuja-Rana-Associates-10-800x527.jpg"
    ],
    [
        "id" => 62,
        "title" => "Appartamento in Centro con Terrazza",
        "description" => "Elegante appartamento in centro città con terrazza privata.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 2,
        "mq" => 75,
        "address" => "Piazza della Repubblica 4, Firenze",
        "lat" => "43.7696",
        "long" => "11.2558",
        "image" => "https://interiorlover.in/wp-content/uploads/2021/04/Tanuja-Rana-Associates-11-800x527.jpg"
    ],
    [
        "id" => 63,
        "title" => "Monolocale con Arredi Moderni e Vista Mare",
        "description" => "Monolocale con arredi moderni e vista mozzafiato sul mare.",
        "beds" => 1,
        "bathrooms" => 1,
        "rooms" => 1,
        "mq" => 50,
        "address" => "Via del Mare 10, Sorrento",
        "lat" => "40.6217",
        "long" => "14.3755",
        "image" => "https://interiorlover.in/wp-content/uploads/2021/04/Tanuja-Rana-Associates-6.jpg"
    ],
    [
        "id" => 64,
        "title" => "Casa di Campagna con Giardino e Fattoria",
        "description" => "Incantevole casa di campagna con ampio giardino e fattoria privata.",
        "beds" => 6,
        "bathrooms" => 4,
        "rooms" => 7,
        "mq" => 200,
        "address" => "Via della Fattoria 8, Siena",
        "lat" => "43.3188",
        "long" => "11.3308",
        "image" => "https://media.istockphoto.com/id/1018717866/it/foto/una-delle-strade-di-milano.jpg?s=1024x1024&w=is&k=20&c=lzA5m47NxUVQ6ScwZ32YPaydiDSQHPr6d__1kU70JPc="
    ],
    [
        "id" => 65,
        "title" => "Appartamento con Area Fitness e Spa",
        "description" => "Moderno appartamento con area fitness e spa privata.",
        "beds" => 2,
        "bathrooms" => 2,
        "rooms" => 3,
        "mq" => 100,
        "address" => "Via del Benessere 12, Bologna",
        "lat" => "44.4949",
        "long" => "11.3426",
        "image" => "https://media.istockphoto.com/id/1355222547/it/foto/architettura-del-novecento-a-milano.jpg?s=1024x1024&w=is&k=20&c=r1Y6gnp_y4MVjYSvx10C64Sw68_ZntZfzmu4P6OnUP4="
    ],
    [
        "id" => 66,
        "title" => "Attico con Panoramica sul Parco",
        "description" => "Lussuoso attico con terrazza e vista panoramica su un grande parco.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 140,
        "address" => "Piazza del Parco 5, Torino",
        "lat" => "45.0703",
        "long" => "7.6869",
        "image" => "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/05/e2/1e/luna-muna.jpg?w=1200&h=-1&s=1"
    ],
    [
        "id" => 67,
        "title" => "Villa in Collina con Vista e Piscina",
        "description" => "Elegante villa situata in collina con vista panoramica e piscina.",
        "beds" => 5,
        "bathrooms" => 3,
        "rooms" => 6,
        "mq" => 250,
        "address" => "Via della Collina 20, Lucca",
        "lat" => "43.8414",
        "long" => "10.5010",
        "image" => "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/37/63/27/habitacion-doble.jpg?w=1200&h=-1&s=1"
    ],
    [
        "id" => 68,
        "title" => "Appartamento con Terrazza e Vista su Palazzo",
        "description" => "Appartamento con una terrazza privata e vista su un palazzo storico in Napoli.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 2,
        "mq" => 80,
        "address" => "Piazza Storica 15, Napoli",
        "lat" => "40.8522",
        "long" => "14.2681",
        "image" => "https://www.kireti.it/wp-content/uploads/2021/04/iStock-1225226886-scaled.jpg"
    ],
    [
        "id" => 69,
        "title" => "Loft con Spazi Aperti e Design Contemporaneo",
        "description" => "Loft con spazi aperti e design contemporaneo, ideale per famiglie.",
        "beds" => 4,
        "bathrooms" => 2,
        "rooms" => 3,
        "mq" => 120,
        "address" => "Via del Design 7, Torino",
        "lat" => "45.0703",
        "long" => "7.6869",
        "image" => "https://www.mansarda.it/wp-content/uploads/2024/09/salotto-768x518.jpg"
    ],
    [
        "id" => 70,
        "title" => "Appartamento con Giardino e Cucina all'Aperto",
        "description" => "Spazioso appartamento con giardino privato e cucina all'aperto.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 110,
        "address" => "Via del Giardino 14, Verona",
        "lat" => "45.4384",
        "long" => "10.9916",
        "image" => "https://www.mansarda.it/wp-content/uploads/2024/09/luce-specchio-768x512.png"
    ],
    [
        "id" => 71,
        "title" => "Villa con Terrazza e Vista sul Lago",
        "description" => "Elegante villa con terrazza e vista panoramica sul lago.",
        "beds" => 6,
        "bathrooms" => 4,
        "rooms" => 7,
        "mq" => 300,
        "address" => "Via del Lago 7, Como",
        "lat" => "45.8081",
        "long" => "9.0852",
        "image" => "https://www.mansarda.it/wp-content/uploads/2024/09/letto-sotto-finestra-1280x864.jpg"
    ],
    [
        "id" => 72,
        "title" => "Appartamento con Terrazza e Vista sui Tetti",
        "description" => "Appartamento con grande terrazza e vista sui tetti della città.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 2,
        "mq" => 70,
        "address" => "Via dei Tetti 12, Roma",
        "lat" => "41.9028",
        "long" => "12.4964",
        "image" => "https://www.mansarda.it/wp-content/uploads/2024/09/sala-giochi-1280x960.jpg"
    ],
    [
        "id" => 73,
        "title" => "Casa con Patio e Vista sul Mare",
        "description" => "Casa con patio esterno e vista spettacolare sul mare.",
        "beds" => 5,
        "bathrooms" => 3,
        "rooms" => 6,
        "mq" => 220,
        "address" => "Via del Mare 33, Catania",
        "lat" => "37.5079",
        "long" => "15.0836",
        "image" => "https://www.fundar.com.ar/resources/original/productos/frida/renders/015.jpg"
    ],
    [
        "id" => 74,
        "title" => "Monolocale con Arredi Eleganti e Vista Città",
        "description" => "Monolocale elegante con vista mozzafiato sulla città.",
        "beds" => 1,
        "bathrooms" => 1,
        "rooms" => 1,
        "mq" => 55,
        "address" => "Via dell'Eleganza 9, Milano",
        "lat" => "45.4642",
        "long" => "9.1899",
        "image" => "https://www.joyjar.it/wp-content/uploads/2018/03/real-estate-3297625_1920-min.jpg"
    ],
    [
        "id" => 75,
        "title" => "Appartamento con Sala Cinema e Jacuzzi",
        "description" => "Moderno appartamento con sala cinema privata e jacuzzi.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 130,
        "address" => "Via del Cinema 8, Bologna",
        "lat" => "44.4949",
        "long" => "11.3426",
        "image" => "https://www.fundar.com.ar/resources/original/productos/frida/renders/005.jpg"
    ],
    [
        "id" => 76,
        "title" => "Terrazza e Vista sul Mare",
        "description" => "Elegante attico con terrazza e vista panoramica sul mare.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 150,
        "address" => "Lungomare 12, Genova",
        "lat" => "44.4056",
        "long" => "8.9462",
        "image" => "https://www.fundar.com.ar/resources/original/productos/frida/renders/009.jpg"
    ],
    [
        "id" => 77,
        "title" => "Appartamento con Giardino e Spa Privata",
        "description" => "Appartamento con giardino privato e zona spa esclusiva.",
        "beds" => 2,
        "bathrooms" => 2,
        "rooms" => 3,
        "mq" => 85,
        "address" => "Via del Relax 6, Torino",
        "lat" => "45.0703",
        "long" => "7.6869",
        "image" => "https://www.fundar.com.ar/resources/original/productos/frida/renders/010.jpg"
    ],
    [
        "id" => 78,
        "title" => "Villa con Vigneti e Piscina",
        "description" => "Affascinante villa con vista sui vigneti e piscina privata.",
        "beds" => 6,
        "bathrooms" => 4,
        "rooms" => 7,
        "mq" => 280,
        "address" => "Via dei Vigneti 18, Chianti",
        "lat" => "43.5500",
        "long" => "11.3045",
        "image" => "https://www.fundar.com.ar/resources/original/productos/frida/renders/011.jpg"
    ],
    [
        "id" => 79,
        "title" => "Appartamento con Vista Panoramica e Terrazza",
        "description" => "Spazioso appartamento con terrazza privata e vista panoramica.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 120,
        "address" => "Piazza Panorama 7, Verona",
        "lat" => "45.4384",
        "long" => "10.9916",
        "image" => "https://www.fundar.com.ar/resources/original/productos/frida/renders/012.jpg"
    ],
    [
        "id" => 80,
        "title" => "Casa con Accesso Privato al Lago",
        "description" => "Casa con accesso diretto al lago e ampio spazio esterno.",
        "beds" => 4,
        "bathrooms" => 3,
        "rooms" => 5,
        "mq" => 180,
        "address" => "Via del Lago 22, Como",
        "lat" => "45.8081",
        "long" => "9.0852",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/290018095.jpg?k=dc32085f610e7b5491cf26b5e23d854996568a7e115524a569bdbdc2743e4463&o=&hp=1"
    ],
    [
        "id" => 81,
        "title" => "Appartamento con Spazi Moderni e Terrazzo",
        "description" => "Moderno appartamento con spazi ampi e terrazzo privato.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 2,
        "mq" => 85,
        "address" => "Via degli Spazi 6, Bologna",
        "lat" => "44.4949",
        "long" => "11.3426",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/597310078.jpg?k=ad77be47ed6a3024ba9b0abb64092303416149c9c9d72ce743e49b17cf8fc552&o=&hp=1"
    ],
    [
        "id" => 82,
        "title" => "Monolocale con Arredi di Design e Vista Città",
        "description" => "Elegante monolocale con arredi di design e vista sulla città.",
        "beds" => 1,
        "bathrooms" => 1,
        "rooms" => 1,
        "mq" => 60,
        "address" => "Via del Design 3, Milano",
        "lat" => "45.4642",
        "long" => "9.1899",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/597307812.jpg?k=1bce17a9d20a04a6a56eaaad1592d0c3395ee81ccc68c713a3ca43ee55db27af&o=&hp=1"
    ],
    [
        "id" => 83,
        "title" => "Appartamento con Spazio Verde e Balcone",
        "description" => "Appartamento con spazio verde condiviso e balcone privato.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 2,
        "mq" => 70,
        "address" => "Via del Verde 8, Firenze",
        "lat" => "43.7696",
        "long" => "11.2558",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/597307848.jpg?k=e25684310a19cd13c577c185420ee8d2765d2d967a5b201405e9297b148955b4&o=&hp=1"
    ],
    [
        "id" => 84,
        "title" => "Attico con Spazio all'Aperto e Vista sui Monti",
        "description" => "Attico esclusivo con ampio spazio all'aperto e vista sulle montagne.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 140,
        "address" => "Via dei Monti 8, Trento",
        "lat" => "46.0670",
        "long" => "11.1217",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/597307418.jpg?k=b26b696a87628a20710b662cb3aede54ac0fb610f69950742e27afffe117b66e&o=&hp=1"
    ],
    [
        "id" => 85,
        "title" => "Appartamento con Piscina e Terrazza",
        "description" => "Moderno appartamento con piscina privata e spaziosa terrazza.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 3,
        "mq" => 110,
        "address" => "Via della Piscina 5, Bologna",
        "lat" => "44.4949",
        "long" => "11.3426",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/597307424.jpg?k=02232b614deebf1f968febb64b1d209f219d8dbfd9833f1c332414aeea599b23&o=&hp=1"
    ],
    [
        "id" => 86,
        "title" => "Casa con Giardino e Terrazzo Vista Mare",
        "description" => "Casa con ampio giardino e terrazzo con vista sul mare.",
        "beds" => 5,
        "bathrooms" => 3,
        "rooms" => 6,
        "mq" => 220,
        "address" => "Via del Mare 18, Catania",
        "lat" => "37.5079",
        "long" => "15.0836",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/597307160.jpg?k=99559255c027812cafbf67a9c56254073994dc442efd113434349674ed9f6dcd&o=&hp=1"
    ],
    [
        "id" => 87,
        "title" => "Monolocale con Vista e Arredi Minimal",
        "description" => "Elegante monolocale con arredi minimal e vista panoramica.",
        "beds" => 1,
        "bathrooms" => 1,
        "rooms" => 1,
        "mq" => 55,
        "address" => "Via Minimal 4, Milano",
        "lat" => "45.4642",
        "long" => "9.1899",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/596625234.jpg?k=6bd7aa5aadd088dae1a032d90af2197b196cda7f9bb58921d2f681f4e3a6322d&o=&hp=1"
    ],
    [
        "id" => 88,
        "title" => "Appartamento con Spa e Arredi Lusso",
        "description" => "Spazioso appartamento con area spa e arredi di lusso.",
        "beds" => 2,
        "bathrooms" => 2,
        "rooms" => 3,
        "mq" => 100,
        "address" => "Via del Lusso 10, Roma",
        "lat" => "41.9028",
        "long" => "12.4964",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/593727682.jpg?k=c69be0c1923c40ec3e53da1313c0f6aa9c23711e85c5b2993b96d470820c7397&o=&hp=1"
    ],
    [
        "id" => 89,
        "title" => "Villa con Giardino e Vista Panoramica",
        "description" => "Villa esclusiva con giardino e vista panoramica sul paesaggio circostante.",
        "beds" => 6,
        "bathrooms" => 4,
        "rooms" => 7,
        "mq" => 300,
        "address" => "Via della Panoramica 15, Lucca",
        "lat" => "43.8414",
        "long" => "10.5010",
        "image" => "https://www.example.com/images/villa_giardino_panoramica.jpg"
    ],
    [
        "id" => 90,
        "title" => "Appartamento con Terrazza e Vista al Tramonto",
        "description" => "Elegante appartamento con terrazza e vista spettacolare al tramonto.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 2,
        "mq" => 75,
        "address" => "Piazza del Tramonto 8, Firenze",
        "lat" => "43.7696",
        "long" => "11.2558",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/593727676.jpg?k=7cbdebe96ae53969395776d15eec37d35848626bb40528c4836d2675342d016e&o=&hp=1"
    ],
    [
        "id" => 91,
        "title" => "Attico Moderno con Piscina e Vista Urbana",
        "description" => "Elegante attico con piscina privata e vista sulla città.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 150,
        "address" => "Corso Milano 14, Milano",
        "lat" => "45.4642",
        "long" => "9.1899",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/596621053.jpg?k=8bbd47290b77e985c45476ad129a3e2a92f05692d84fc6ae6236ff4f6d60c5e8&o=&hp=1"
    ],
    [
        "id" => 92,
        "title" => "Appartamento con Terrazzo e Giardino Privato",
        "description" => "Spazioso appartamento con terrazzo e giardino privato.",
        "beds" => 2,
        "bathrooms" => 2,
        "rooms" => 3,
        "mq" => 110,
        "address" => "Via del Giardino 9, Bologna",
        "lat" => "44.4949",
        "long" => "11.3426",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/596625701.jpg?k=7055d3e14c35fd7bc0487b5a7ed8c7b21861e063ce569a5326511d0c6c3bda15&o=&hp=1"
    ],
    [
        "id" => 93,
        "title" => "Villa con Vista Montagna e Piscina",
        "description" => "Luxuosa villa con vista panoramica sulle montagne e piscina.",
        "beds" => 5,
        "bathrooms" => 4,
        "rooms" => 6,
        "mq" => 250,
        "address" => "Via delle Montagne 12, Trento",
        "lat" => "46.0670",
        "long" => "11.1217",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/431976898.jpg?k=f7c244318efe8d5e1f9c4ce438f3c4d6ecefebef75e216db564a49d5e872b9bf&o=&hp=1"
    ],
    [
        "id" => 94,
        "title" => "Monolocale con Terrazzo e Vista Mare",
        "description" => "Moderno monolocale con terrazzo e vista mozzafiato sul mare.",
        "beds" => 1,
        "bathrooms" => 1,
        "rooms" => 1,
        "mq" => 50,
        "address" => "Via del Mare 5, Napoli",
        "lat" => "40.8522",
        "long" => "14.2681",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/415429981.jpg?k=de65f45b21cd3cf9b793b0e1f1c4cd5667b7d48391903e0f48a5b59c479743df&o=&hp=1"
    ],
    [
        "id" => 95,
        "title" => "Appartamento con Arredi Contemporanei e Balcone",
        "description" => "Elegante appartamento con arredi contemporanei e balcone privato.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 2,
        "mq" => 80,
        "address" => "Via dei Contemporanei 7, Roma",
        "lat" => "41.9028",
        "long" => "12.4964",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/416878275.jpg?k=df2c5128707771866f161594ba57dcd92b1ce2e9c7c07f94b7ea5e466c0608e0&o=&hp=1"
    ],
    [
        "id" => 96,
        "title" => "Casa Rustica con Spazio Esterno e Vista Collina",
        "description" => "Casa rustica con ampio spazio esterno e vista sulle colline.",
        "beds" => 4,
        "bathrooms" => 3,
        "rooms" => 5,
        "mq" => 180,
        "address" => "Via della Collina 10, Siena",
        "lat" => "43.3183",
        "long" => "11.3306",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/431976848.jpg?k=02f4e5e5992ed6f86ae9b79b9e3da6176703ad0d4ed1c59973fc429166dd9857&o=&hp=1"
    ],
    [
        "id" => 97,
        "title" => "Appartamento di Lusso con Spa e Terrazza",
        "description" => "Appartamento di lusso con spa privata e ampia terrazza.",
        "beds" => 2,
        "bathrooms" => 2,
        "rooms" => 3,
        "mq" => 120,
        "address" => "Via del Lusso 15, Milano",
        "lat" => "45.4642",
        "long" => "9.1899",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/431976867.jpg?k=782164f1177d6c67514b952217838c25a2129ea0c22ba814fe1d56f5558d9a5f&o=&hp=1"
    ],
    [
        "id" => 98,
        "title" => "Attico con Vista Urbana e Terrazza",
        "description" => "Attico elegante con vista sulla città e terrazza privata.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 140,
        "address" => "Via della Vista 20, Torino",
        "lat" => "45.0703",
        "long" => "7.6869",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/463896552.jpg?k=fd5eb559e7d9306f22e27dfd1f0432749078d9d12dd235e5f34382c1e4e2f8a2&o=&hp=1"
    ],
    [
        "id" => 99,
        "title" => "Villa con Giardino e Area Barbecue",
        "description" => "Spaziosa villa con giardino e area barbecue per intrattenere ospiti.",
        "beds" => 6,
        "bathrooms" => 4,
        "rooms" => 7,
        "mq" => 280,
        "address" => "Via del Barbecue 8, Verona",
        "lat" => "45.4384",
        "long" => "10.9916",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/286641909.jpg?k=eaf8d3ed577490aff03241247bbb48574e0209ae9232b9ddebffdce0c78d893d&o=&hp=1"
    ],
    [
        "id" => 100,
        "title" => "Appartamento con Accesso Diretto alla Spiaggia",
        "description" => "Appartamento con accesso diretto alla spiaggia e vista mare.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 130,
        "address" => "Via della Spiaggia 11, Catania",
        "lat" => "37.5079",
        "long" => "15.0836",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/171446792.jpg?k=600b5974d4b7e1f0758a2cd35d133a9eb2c41e41fbd691d456c902c593bfe36b&o=&hp=1"
    ],
    [
        "id" => 101,
        "title" => "Monolocale Elegante con Vista sulla Città",
        "description" => "Elegante monolocale con arredi di alta qualità e vista sulla città.",
        "beds" => 1,
        "bathrooms" => 1,
        "rooms" => 1,
        "mq" => 65,
        "address" => "Via della Vista 7, Firenze",
        "lat" => "43.7696",
        "long" => "11.2558",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/298180178.jpg?k=a44fe1f4d1b957aa429de4269c44154ce57078f0f3cc89a51b62a563cf640b64&o=&hp=1"
    ],
    [
        "id" => 102,
        "title" => "Appartamento con Giardino e Area Lounge",
        "description" => "Appartamento con giardino privato e area lounge per relax all'aperto.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 2,
        "mq" => 75,
        "address" => "Via dell'Outdoor 12, Bologna",
        "lat" => "44.4949",
        "long" => "11.3426",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/208211912.jpg?k=c025b136f5932e35c8860c4e6b91773cef407eaa03b74acb7b1d96dd40440848&o=&hp=1"
    ],
    [
        "id" => 103,
        "title" => "Villa con Piscina e Vista Panoramica",
        "description" => "Villa elegante con piscina privata e vista panoramica.",
        "beds" => 5,
        "bathrooms" => 4,
        "rooms" => 6,
        "mq" => 260,
        "address" => "Via del Panorama 14, Lucca",
        "lat" => "43.8414",
        "long" => "10.5010",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/208213076.jpg?k=5498ed768cfc5db6ea89d0c5849dbfd5f76a74bea5cbf01224b2d81160082fa9&o=&hp=1"
    ],
    [
        "id" => 104,
        "title" => "Attico con Arredi di Design e Terrazza",
        "description" => "Attico con arredi di design e spaziosa terrazza per godere della vista.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 160,
        "address" => "Via del Design 8, Roma",
        "lat" => "41.9028",
        "long" => "12.4964",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/208213005.jpg?k=533562a5972ee32f31001adf66ddc3f8f0cfdb329a274cf9b54b7ef9c342f900&o=&hp=1"
    ],
    [
        "id" => 105,
        "title" => "Casa con Piscina e Giardino Botanico",
        "description" => "Casa con piscina privata e giardino botanico per un soggiorno rilassante.",
        "beds" => 4,
        "bathrooms" => 3,
        "rooms" => 5,
        "mq" => 220,
        "address" => "Via del Botanico 11, Firenze",
        "lat" => "43.7696",
        "long" => "11.2558",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/208213504.jpg?k=6c782961dfa30a782a9c9a09ebd0d707fbab17fb9f40a6b199751a262932b862&o=&hp=1"
    ],
    [
        "id" => 106,
        "title" => "Appartamento con Vista e Terrazza Coperta",
        "description" => "Appartamento con splendida vista e terrazza coperta per godere della vista.",
        "beds" => 2,
        "bathrooms" => 2,
        "rooms" => 3,
        "mq" => 100,
        "address" => "Via della Vista Coperta 5, Torino",
        "lat" => "45.0703",
        "long" => "7.6869",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/208213501.jpg?k=e999bd93542fd991ee0265757f7c57a14075bea8c6d23576b9cc450fa1a196ec&o=&hp=1"
    ],
    [
        "id" => 107,
        "title" => "Monolocale con Vista sulla Montagna",
        "description" => "Moderno monolocale con vista panoramica sulle montagne.",
        "beds" => 1,
        "bathrooms" => 1,
        "rooms" => 1,
        "mq" => 55,
        "address" => "Via della Montagna 3, Bolzano",
        "lat" => "46.4983",
        "long" => "11.3544",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/208213509.jpg?k=abcd39b15aed6865cda8c0511bda3833ff57509a618b07551e2e7292841ecb87&o=&hp=1"
    ],
    [
        "id" => 108,
        "title" => "Appartamento con Piscina e Spazio Esterno",
        "description" => "Appartamento con piscina condivisa e ampio spazio esterno.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 120,
        "address" => "Via del Relax 6, Verona",
        "lat" => "45.4384",
        "long" => "10.9916",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/208211914.jpg?k=2cfcb3fc40769110ae5b5a803ffbffffb4af9c115b5e4f3f1fac93150bc106e5&o=&hp=1"
    ],
    [
        "id" => 109,
        "title" => "Villa con Area Fitness e Sauna",
        "description" => "Villa spaziosa con area fitness e sauna privata per il benessere.",
        "beds" => 5,
        "bathrooms" => 4,
        "rooms" => 6,
        "mq" => 230,
        "address" => "Via del Fitness 9, Siena",
        "lat" => "43.3183",
        "long" => "11.3306",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/208203879.jpg?k=40ca34182833a830e32a43325473eb24e6f861a44cc7b4207033bc6456c75c94&o=&hp=1"
    ],
    [
        "id" => 110,
        "title" => "Appartamento con Arredi Eleganti e Terrazza",
        "description" => "Elegante appartamento con arredi sofisticati e terrazza per relax.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 2,
        "mq" => 85,
        "address" => "Via degli Eleganti 10, Milano",
        "lat" => "45.4642",
        "long" => "9.1899",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/208213522.jpg?k=335c6c897e4ad0dd6dcfe134c89493bd90edf32b6ca94197923bef9d39fe2638&o=&hp=1"
    ],
    [
        "id" => 111,
        "title" => "Casa con Patio e Area Picnic",
        "description" => "Casa con patio accogliente e area picnic per pranzi all'aperto.",
        "beds" => 4,
        "bathrooms" => 2,
        "rooms" => 5,
        "mq" => 200,
        "address" => "Via del Picnic 13, Bologna",
        "lat" => "44.4949",
        "long" => "11.3426",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/208213512.jpg?k=7892b4d102268d19b767398ff77b497c9258299490ca5545b823600ce4650985&o=&hp=1"
    ],
    [
        "id" => 112,
        "title" => "Appartamento con Terrazza e Vista sul Parco",
        "description" => "Moderno appartamento con terrazza privata e vista sul parco.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 2,
        "mq" => 80,
        "address" => "Via del Parco 6, Torino",
        "lat" => "45.0703",
        "long" => "7.6869",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/208213083.jpg?k=c090ccf0c2f299b13ff7bef05b952083fc5a60dadcdeb0ef3e3ff2ee411d8bbc&o=&hp=1"
    ],
    [
        "id" => 113,
        "title" => "Monolocale con Arredi Moderni e Vista Città",
        "description" => "Monolocale elegante con arredi moderni e vista panoramica sulla città.",
        "beds" => 1,
        "bathrooms" => 1,
        "rooms" => 1,
        "mq" => 60,
        "address" => "Via del Moderno 8, Firenze",
        "lat" => "43.7696",
        "long" => "11.2558",
        "image" => "https://www.example.com/images/monolocale_arredi_moderni.jpg"
    ],
    [
        "id" => 114,
        "title" => "Villa con Vista Lago e Giardino Privato",
        "description" => "Spaziosa villa con vista lago e giardino privato per il relax.",
        "beds" => 5,
        "bathrooms" => 4,
        "rooms" => 6,
        "mq" => 270,
        "address" => "Via del Lago 7, Como",
        "lat" => "45.8088",
        "long" => "9.0853",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/219224057.jpg?k=62774538b55804da258f2bb599c084d0e3e2f9e79088fa8e4dc1a2b717d7e54f&o=&hp=1"
    ],
    [
        "id" => 115,
        "title" => "Appartamento con Giardino e Spazio per Famiglie",
        "description" => "Appartamento spazioso con giardino privato e area giochi per famiglie.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 130,
        "address" => "Via della Famiglia 5, Napoli",
        "lat" => "40.8522",
        "long" => "14.2681",
        "image" => "https://interiorlover.in/wp-content/uploads/2021/04/Tanuja-Rana-Associates-1.jpg"
    ],
    [
        "id" => 116,
        "title" => "Attico con Vista Panoramica e Jacuzzi",
        "description" => "Attico lussuoso con vista panoramica e jacuzzi privata.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 150,
        "address" => "Via della Jacuzzi 4, Milano",
        "lat" => "45.4642",
        "long" => "9.1899",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/208213492.jpg?k=6a45472225b271291ebc95cec230b1c5123e2403844c6873680b2f8743bfe6fe&o=&hp=1"
    ],
    [
        "id" => 117,
        "title" => "Appartamento con Piscina e Vista Mare",
        "description" => "Appartamento moderno con piscina condivisa e vista mare spettacolare.",
        "beds" => 2,
        "bathrooms" => 2,
        "rooms" => 3,
        "mq" => 100,
        "address" => "Via del Mare 12, Catania",
        "lat" => "37.5079",
        "long" => "15.0836",
        "image" => "https://interiorlover.in/wp-content/uploads/2021/04/Tanuja-Rana-Associates-3.jpg"
    ],
    [
        "id" => 118,
        "title" => "Casa con Terrazza e Vista sulle Colline",
        "description" => "Accogliente casa con terrazza e vista mozzafiato sulle colline.",
        "beds" => 4,
        "bathrooms" => 2,
        "rooms" => 5,
        "mq" => 190,
        "address" => "Via delle Colline 8, Siena",
        "lat" => "43.3183",
        "long" => "11.3306",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/562372914.jpg?k=cae3ff8f21bda0124d26e5aff8c3fb4b86360b14047fcef44255cad7a24ab83e&o=&hp=1"
    ],
    [
        "id" => 119,
        "title" => "Appartamento con Arredi di Lusso e Vista Città",
        "description" => "Elegante appartamento con arredi di lusso e vista sulla città.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 2,
        "mq" => 90,
        "address" => "Via del Lusso 14, Roma",
        "lat" => "41.9028",
        "long" => "12.4964",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/562371063.jpg?k=4cf2657f02038c96f831deba94c981d42fa06b63adb3d981c0c9c18113b73b29&o=&hp=1"
    ],
    [
        "id" => 120,
        "title" => "Monolocale con Terrazza e Vista Panoramica",
        "description" => "Moderno monolocale con terrazza e vista panoramica sulla città.",
        "beds" => 1,
        "bathrooms" => 1,
        "rooms" => 1,
        "mq" => 70,
        "address" => "Via della Terrazza 9, Torino",
        "lat" => "45.0703",
        "long" => "7.6869",
        "image" => "https://interiorlover.in/wp-content/uploads/2021/04/Tanuja-Rana-Associates-5.jpg"
    ]
];
