<?php

return [
    [
        "id" => 1,
        "title" => "Appartamento al Centro Storico",
        "description" => "Accogliente appartamento nel cuore della città, vicino a tutti i servizi.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 3,
        "mq" => 80,
        "address" => "Via Roma 1, Roma",
        "lat" => "41.902782",
        "long" => "12.496366",
        "image" => "https://trovacasacomo.it/preview/5936/imm_3303-1200-800.jpg"
    ],
    [
        "id" => 2,
        "title" => "Villetta con Giardino",
        "description" => "Spaziosa villetta immersa nel verde con giardino privato.",
        "beds" => 4,
        "bathrooms" => 2,
        "rooms" => 5,
        "mq" => 150,
        "address" => "Via dei Giardini 10, Milano",
        "lat" => "45.464203",
        "long" => "9.189982",
        "image" => "https://www.casavacanzeaffitti.it/wp-content/uploads/2021/02/IMG_3366.jpg"
    ],
    [
        "id" => 3,
        "title" => "Attico Vista Mare",
        "description" => "Luminoso attico con splendida vista sul mare.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 120,
        "address" => "Via del Mare 5, Napoli",
        "lat" => "40.851798",
        "long" => "14.268120",
        "image" => "https://www.hotelmeeting.com/wp-content/uploads/2021/07/5038.jpg"
    ],
    [
        "id" => 4,
        "title" => "Appartamento Moderno",
        "description" => "Appartamento completamente ristrutturato in stile moderno.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 3,
        "mq" => 90,
        "address" => "Via Garibaldi 15, Torino",
        "lat" => "45.070312",
        "long" => "7.686856",
        "image" => "https://www.startpreventivi.it/wp-content/themes/Avada-Child-Theme/images/Blog/Case-Appartamenti/Appartamento-moderno-elegante/5-appartamento-moderno-elegante.jpg"
    ],
    [
        "id" => 5,
        "title" => "Casa Vacanze sul Lago",
        "description" => "Casa vacanze con accesso diretto al lago e vista panoramica.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 3,
        "mq" => 100,
        "lat" => "45.808059",
        "long" => "9.085176",
        "address" => "Via Lungolago 20, Como",
        "image" => "https://blog.casa.it/wp-content/uploads/2014/06/casa_al_lago6.jpg"
    ],
    [
        "id" => 6,
        "title" => "Appartamento in Zona Universitaria",
        "description" => "Perfetto per studenti, a pochi passi dall'università.",
        "beds" => 1,
        "bathrooms" => 1,
        "rooms" => 2,
        "mq" => 60,
        "lat" => "44.494887",
        "long" => "11.342616",
        "address" => "Via Zamboni 33, Bologna",
        "image" => "https://www.leresidenzedelcampus.it/wp-content/uploads/2016/03/affitto-appartamenti-parma.jpg"
    ],
    [
        "id" => 7,
        "title" => "Appartamento in Villa d'Epoca",
        "description" => "Splendido appartamento in villa d'epoca, immerso nel verde.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 130,
        "address" => "Via Verdi 5, Firenze",
        "lat" => "43.769562",
        "long" => "11.255814",
        "image" => "https://trepievi.com/wp-content/uploads/2021/09/Esterni-Appartamenti-Menaggio-Rif.MA023H-14_rid.jpg"
    ],
    [
        "id" => 8,
        "title" => "Monolocale Arredato",
        "description" => "Monolocale completamente arredato in zona centrale.",
        "beds" => 1,
        "bathrooms" => 1,
        "rooms" => 1,
        "mq" => 40,
        "address" => "Corso Umberto I 10, Bari",
        "lat" => "41.117143",
        "long" => "16.871871",
        "image" => "https://mondodesign.it/wp-content/uploads/2016/07/Arredare-Monolocale-86.jpg"
    ],
    [
        "id" => 9,
        "title" => "Trilocale con Vista",
        "description" => "Appartamento trilocale con vista mozzafiato sulla città.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 3,
        "mq" => 85,
        "address" => "Via Toledo 12, Napoli",
        "lat" => "40.851798",
        "long" => "14.268120",
        "image" => "https://it.gardalive.com/var/21925/storage/images/media/immagini/ufficio-manerba/man200/man200-3/614941-1-ita-IT/man200-3_full25.jpg"
    ],
    [
        "id" => 10,
        "title" => "Loft Industriale",
        "description" => "Loft dal design industriale in ex fabbrica ristrutturata.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 2,
        "mq" => 100,
        "address" => "Via Bovisasca 16, Milano",
        "lat" => "45.464203",
        "long" => "9.189982",
        "image" => "https://cdn.home-designing.com/wp-content/uploads/2015/03/wood-paneled-loft.jpg"
    ]
];
